### ISSUE TITLE
[BUG] Clipboard operations of FastAsyncWorldEdit will not be recorded.

### ISSUE THREAD

**Issue by Chuanwise** [prism/PrismRefracted#54]
**Describe the bug**
I set `prism.tracking.world-edit` to `true` and copied some buildings, then pasted it. `/pr near` given nothing record near buildings pasted. 

**To Reproduce**
1. Install FastAsyncWorldEdit and Prism to your server, then config them properly.
2. Use `//copy` to copy some buildings.
3. Paste them.
4. Execute `/pr near` near buildings pasted.

**Expected behavior**
`/pr near` will display records related to pasting operations.

**Server (please complete the following information):**
  - Prism Version: 3.6.0
  - Server Type: Purpur
  - Server Version: 1.19.2

**Comment by Rothes** [comment]
FAWE doesn't call `AbstractDelegateExtent#setBlock` on paste so we can't log it
