### ISSUE TITLE
[FEATURE] PostgreSQL Support

### ISSUE THREAD

**Issue by kpAjun** [prism/PrismRefracted#81]
**Describe the solution you'd like**
As a write-intensive application, Prism should work better with PostgreSQL than MySQL in some cases, which makes adding support for PostgreSQL reasonable. This is just a humble suggestion and I really appreciate your work on this wonderful plugin. Thank you very much!

**Comment by viveleroi** [comment]
PostgreSQL is being added to v4 which is in progress but has no timeline due to jooq licensing issues we're waiting on them to fix. v3 will never be updated with this.
